# Generated by Django 2.1.1 on 2018-09-12 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0003_auto_20180903_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteMedSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_age', models.IntegerField()),
                ('profile_image', models.URLField()),
                ('tib_anterior_lle', jsonfield.fields.JSONField()),
                ('tib_anterior_rle', jsonfield.fields.JSONField()),
                ('peroneals_rle', jsonfield.fields.JSONField()),
                ('peroneals_lle', jsonfield.fields.JSONField()),
                ('med_gastro_rle', jsonfield.fields.JSONField()),
                ('med_gastro_lle', jsonfield.fields.JSONField()),
                ('lat_gastro_rle', jsonfield.fields.JSONField()),
                ('lat_gastro_lle', jsonfield.fields.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.TextField()),
                ('treatment', models.TextField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
