# Generated by Django 2.1.1 on 2018-09-26 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0004_athletemedsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peroneals_rle', jsonfield.fields.JSONField()),
                ('peroneals_lle', jsonfield.fields.JSONField()),
                ('med_gastro_lle', jsonfield.fields.JSONField()),
                ('med_gastro_rle', jsonfield.fields.JSONField()),
                ('tib_anterior_lle', jsonfield.fields.JSONField()),
                ('tib_anterior_rle', jsonfield.fields.JSONField()),
                ('lat_gastro_lle', jsonfield.fields.JSONField()),
                ('lat_gastro_rle', jsonfield.fields.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.TextField()),
                ('treatment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peroneals_rle', jsonfield.fields.JSONField()),
                ('peroneals_lle', jsonfield.fields.JSONField()),
                ('med_gastro_lle', jsonfield.fields.JSONField()),
                ('med_gastro_rle', jsonfield.fields.JSONField()),
                ('tib_anterior_lle', jsonfield.fields.JSONField()),
                ('tib_anterior_rle', jsonfield.fields.JSONField()),
                ('lat_gastro_lle', jsonfield.fields.JSONField()),
                ('lat_gastro_rle', jsonfield.fields.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.TextField()),
                ('treatment', models.TextField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Report',
            fields=[
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='college_api.Player')),
                ('user_age', models.IntegerField()),
                ('profile_image', models.URLField()),
                ('tib_anterior_lle', jsonfield.fields.JSONField()),
                ('tib_anterior_rle', jsonfield.fields.JSONField()),
                ('peroneals_rle', jsonfield.fields.JSONField()),
                ('peroneals_lle', jsonfield.fields.JSONField()),
                ('med_gastro_rle', jsonfield.fields.JSONField()),
                ('med_gastro_lle', jsonfield.fields.JSONField()),
                ('lat_gastro_rle', jsonfield.fields.JSONField()),
                ('lat_gastro_lle', jsonfield.fields.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.TextField()),
                ('treatment', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_api.Player'),
        ),
        migrations.AddField(
            model_name='player',
            name='team_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='college_api.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='trainer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
