# Generated by Django 2.1.1 on 2018-09-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0005_auto_20180926_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_report',
            name='lat_gastro_lle',
        ),
        migrations.RemoveField(
            model_name='medical_report',
            name='lat_gastro_rle',
        ),
        migrations.RemoveField(
            model_name='medical_report',
            name='med_gastro_lle',
        ),
        migrations.RemoveField(
            model_name='medical_report',
            name='med_gastro_rle',
        ),
        migrations.RemoveField(
            model_name='medical_report',
            name='peroneals_lle',
        ),
        migrations.RemoveField(
            model_name='medical_report',
            name='peroneals_rle',
        ),
        migrations.RemoveField(
            model_name='medical_report',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='medical_report',
            name='tib_anterior_lle',
        ),
        migrations.RemoveField(
            model_name='medical_report',
            name='tib_anterior_rle',
        ),
        migrations.AddField(
            model_name='medical_report',
            name='injuries',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
