# Generated by Django 2.1.1 on 2018-09-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0006_auto_20180926_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_report',
            old_name='assessment',
            new_name='drug_allergies',
        ),
        migrations.RenameField(
            model_name='medical_report',
            old_name='treatment',
            new_name='surgeries',
        ),
        migrations.AddField(
            model_name='medical_report',
            name='medications',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
