# Generated by Django 2.1.1 on 2018-09-27 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0007_auto_20180926_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='player',
            new_name='player_profile',
        ),
    ]
