# Generated by Django 2.1.1 on 2018-09-26 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0008_playertest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='session',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RemoveField(
            model_name='medical_report',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='medical_report',
            name='user_age',
        ),
        migrations.AddField(
            model_name='medical_report',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medical_report',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college_api.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='user_age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medical_report',
            name='injuries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_api.Injury'),
        ),
        migrations.AlterField(
            model_name='medical_report',
            name='medications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_api.Medication'),
        ),
        migrations.AlterField(
            model_name='medical_report',
            name='surgeries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_api.Surgery'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_api.Team'),
        ),
    ]
