# Generated by Django 2.1.1 on 2018-09-27 00:26

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0008_auto_20180927_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='assessment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='lat_gastro_lle',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='lat_gastro_rle',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='med_gastro_lle',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='med_gastro_rle',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='peroneals_lle',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='peroneals_rle',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='tib_anterior_lle',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='tib_anterior_rle',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='treatment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
