# Generated by Django 2.1.1 on 2018-09-27 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0009_auto_20180927_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='trainer_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
