# Generated by Django 2.1.1 on 2018-10-05 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0010_session_trainer_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='team_name',
            new_name='team',
        ),
        migrations.AlterField(
            model_name='session',
            name='player_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_api.Player'),
        ),
    ]
