# Generated by Django 2.1.1 on 2018-10-06 22:10

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0011_auto_20181005_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='peroneals_rle',
            field=jsonfield.fields.JSONField(blank=True, default=list, null=True),
        ),
    ]
