# Generated by Django 2.1.1 on 2018-10-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0013_auto_20181007_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
    ]
