# Generated by Django 2.1.1 on 2018-10-15 16:00

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0014_injury'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_leg_length', jsonfield.fields.JSONField(blank=True, null=True)),
                ('right_leg_length', jsonfield.fields.JSONField(blank=True, null=True)),
                ('postmedial_direction_rle', jsonfield.fields.JSONField(blank=True, null=True)),
                ('postmedial_direction_lle', jsonfield.fields.JSONField(blank=True, null=True)),
                ('ant_direction_rle', jsonfield.fields.JSONField(blank=True, null=True)),
                ('ant_direction_lle', jsonfield.fields.JSONField(blank=True, null=True)),
                ('post_lateral_direction_lle', jsonfield.fields.JSONField(blank=True, null=True)),
                ('post_lateral_direction_rle', jsonfield.fields.JSONField(blank=True, null=True)),
                ('composite_score', jsonfield.fields.JSONField(blank=True, null=True)),
                ('assessment', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('player_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_api.Player')),
            ],
        ),
    ]
