# Generated by Django 2.1.1 on 2018-10-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0015_composite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composite',
            name='ant_direction_lle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='composite',
            name='ant_direction_rle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='composite',
            name='composite_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='composite',
            name='left_leg_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='composite',
            name='post_lateral_direction_lle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='composite',
            name='post_lateral_direction_rle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='composite',
            name='postmedial_direction_lle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='composite',
            name='postmedial_direction_rle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='composite',
            name='right_leg_length',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
