# Generated by Django 2.1.1 on 2018-10-16 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0016_auto_20181015_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='composite',
            name='risk_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_api.Injury'),
        ),
    ]
