# Generated by Django 2.1.1 on 2018-10-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0017_composite_risk_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composite',
            old_name='composite_score',
            new_name='composite_score_lle',
        ),
        migrations.RenameField(
            model_name='composite',
            old_name='postmedial_direction_lle',
            new_name='post_medial_direction_lle',
        ),
        migrations.RenameField(
            model_name='composite',
            old_name='postmedial_direction_rle',
            new_name='post_medial_direction_rle',
        ),
        migrations.AddField(
            model_name='composite',
            name='composite_score_rle',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
