# Generated by Django 2.1.1 on 2018-10-24 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0018_auto_20181016_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='composite',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
