# Generated by Django 2.1.1 on 2018-12-13 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0019_composite_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peroneals_rle', jsonfield.fields.JSONField(blank=True, null=True)),
                ('peroneals_lle', jsonfield.fields.JSONField(blank=True, null=True)),
                ('med_gastro_lle', jsonfield.fields.JSONField(blank=True, null=True)),
                ('meg_gastro_rle', jsonfield.fields.JSONField(blank=True, null=True)),
                ('tib_anterior_lle', jsonfield.fields.JSONField(blank=True, null=True)),
                ('tib_anterior_rle', jsonfield.fields.JSONField(blank=True, null=True)),
                ('lat_gastro_lle', jsonfield.fields.JSONField(blank=True, null=True)),
                ('lat_gastro_rle', jsonfield.fields.JSONField(blank=True, null=True)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('assessment', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('player_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_api.Player')),
                ('trainer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='athletemedsession',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='athletemedsession',
            name='user_age',
        ),
        migrations.AddField(
            model_name='athletemedsession',
            name='player_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_api.Player'),
        ),
    ]
