# Generated by Django 2.1.1 on 2018-12-16 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0020_auto_20181213_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionlog',
            old_name='meg_gastro_rle',
            new_name='med_gastro_rle',
        ),
    ]
