# Generated by Django 2.1.1 on 2018-12-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0021_auto_20181216_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlog',
            name='created_on',
            field=models.DateField(auto_now_add=True, blank=True, null=True),
            preserve_default=False,
        ),
    ]
