# Generated by Django 2.1.1 on 2018-12-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0022_auto_20181216_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlog',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
