# Generated by Django 2.1.1 on 2018-12-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0024_auto_20181216_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionlog',
            name='created_on',
        ),
    ]
