# Generated by Django 2.1.1 on 2018-12-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0025_remove_sessionlog_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionlog',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
