# Generated by Django 2.1.1 on 2019-01-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0027_sessionlog_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletemedsession',
            name='user_age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
