# Generated by Django 2.1.1 on 2019-01-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0029_auto_20190118_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='mvc',
            name='peroneals_rle',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
