# Generated by Django 2.1.1 on 2019-02-26 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0030_mvc_peroneals_rle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MVCType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mvc_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='mvc',
            name='mvc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_api.MVCType'),
        ),
    ]
