# Generated by Django 2.1.1 on 2019-02-26 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0031_auto_20190226_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvc',
            name='mvc',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='college_api.MVCType'),
            preserve_default=False,
        ),
    ]
