# Generated by Django 2.1.1 on 2019-02-27 22:34

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0034_auto_20190227_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='mvclog',
            name='peroneals_rle',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
