# Generated by Django 2.1.1 on 2019-03-06 17:56

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0035_mvclog_peroneals_rle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posterior_lateral', jsonfield.fields.JSONField(blank=True, null=True)),
                ('posterior_medial', jsonfield.fields.JSONField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_api.Player')),
            ],
        ),
        migrations.CreateModel(
            name='YBalanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y_balance_direction', models.CharField(max_length=255)),
            ],
        ),
    ]
