# Generated by Django 2.1.1 on 2019-03-06 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0036_playerprofile_ybalancetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='user_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
