# Generated by Django 2.1.1 on 2019-03-07 01:23

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0037_playerprofile_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='posterior_lateral',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='posterior_medial',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='lat_gastro',
            field=jsonfield.fields.JSONField(blank=True, default={'left': {'effeciency_score': 0, 'exhaustion': [0, 0, 0], 'mvc': 0}, 'right': {'effeciency_score': 0, 'exhaustion': [0, 0, 0], 'mvc': 0}}, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='med_gastro',
            field=jsonfield.fields.JSONField(blank=True, default={'left': {'effeciency_score': 0, 'exhaustion': [0, 0, 0], 'mvc': 0}, 'right': {'effeciency_score': 0, 'exhaustion': [0, 0, 0], 'mvc': 0}}, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='peroneals',
            field=jsonfield.fields.JSONField(blank=True, default={'left': {'effeciency_score': 0, 'exhaustion': [0, 0, 0], 'mvc': 0}, 'right': {'effeciency_score': 0, 'exhaustion': [0, 0, 0], 'mvc': 0}}, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='tib_anterior',
            field=jsonfield.fields.JSONField(blank=True, default={'left': {'effeciency_score': 0, 'exhaustion': [0, 0, 0], 'mvc': 0}, 'right': {'effeciency_score': 0, 'exhaustion': [0, 0, 0], 'mvc': 0}}, null=True),
        ),
    ]
