# Generated by Django 2.1.1 on 2019-03-15 16:51

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('college_api', '0038_auto_20190307_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='lat_gastro',
            field=jsonfield.fields.JSONField(blank=True, default={'left': {'effeciency_score': 0, 'exhaustion': {'maxEffeciency': 0, 'minEffeciency': 0, 'subMaxEffeciency': 0}, 'mvc': 0}, 'right': {'effeciency_score': 0, 'exhaustion': {'maxEffeciency': 0, 'minEffeciency': 0, 'subMaxEffeciency': 0}, 'mvc': 0}}, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='med_gastro',
            field=jsonfield.fields.JSONField(blank=True, default={'left': {'effeciency_score': 0, 'exhaustion': {'maxEffeciency': 0, 'minEffeciency': 0, 'subMaxEffeciency': 0}, 'mvc': 0}, 'right': {'effeciency_score': 0, 'exhaustion': {'maxEffeciency': 0, 'minEffeciency': 0, 'subMaxEffeciency': 0}, 'mvc': 0}}, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='peroneals',
            field=jsonfield.fields.JSONField(blank=True, default={'left': {'effeciency_score': 0, 'exhaustion': {'maxEffeciency': 0, 'minEffeciency': 0, 'subMaxEffeciency': 0}, 'mvc': 0}, 'right': {'effeciency_score': 0, 'exhaustion': {'maxEffeciency': 0, 'minEffeciency': 0, 'subMaxEffeciency': 0}, 'mvc': 0}}, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='tib_anterior',
            field=jsonfield.fields.JSONField(blank=True, default={'left': {'effeciency_score': 0, 'exhaustion': {'maxEffeciency': 0, 'minEffeciency': 0, 'subMaxEffeciency': 0}, 'mvc': 0}, 'right': {'effeciency_score': 0, 'exhaustion': {'maxEffeciency': 0, 'minEffeciency': 0, 'subMaxEffeciency': 0}, 'mvc': 0}}, null=True),
        ),
    ]
